version: "3.8"

services:
  backend:
    image: mouhebboubaker2/backend:latest
    ports:
      - "3500:3500"
    networks:
      - app-network

  frontend:
    image: mouhebboubaker2/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge