name: CI - Build and Test

on:
  push:
    branches:
      - branchHatem
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend Testing
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Backend Tests
        working-directory: ./backend
        #run: npm test
        run: echo "there is no tests yet"

      # Frontend Testing
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: echo "No tests yet"
        #run: npm test
